from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains
import time
import random
from selenium.webdriver.support.ui import Select
driver=webdriver.Chrome()
driver.get('https://tutorialsninja.com/demo/')
driver.maximize_window()
phones=driver.find_element(By.XPATH,"//ul[@class='nav navbar-nav']//a[contains(text(),'Phones & PDAs')]")
phones.click()
iphone=driver.find_element(By.XPATH,"//a[normalize-space()='iPhone']")
iphone.click()
time.sleep(1)
first_pic=driver.find_element(By.XPATH,"//li[1]//a[1]//img[1]")
first_pic.click()
time.sleep(2)
next_click=driver.find_element(By.XPATH,"//button[@title='Next (Right arrow key)']")
for i in range(0,5):
    next_click.click()
    time.sleep(2)
driver.save_screenshot('screenshot#'+str(random.randint(0,101))+' .png')

x_button=driver.find_element(By.XPATH,'//button[@title="Close (Esc)"]')
x_button.click()
time.sleep(1)
quantity=driver.find_element(By.XPATH,"//input[@id='input-quantity']")
quantity.click()
time.sleep(1)
quantity.clear()
time.sleep(1)
quantity.send_keys('2')
time.sleep(1)
# add_to_cart=driver.find_element(By.XPATH,"//button[@id='button-cart']")
# add_to_cart.click()
# time.sleep(1)
laptops=driver.find_element(By.XPATH,'//a[@class="dropdown-toggle"][normalize-space()="Laptops & Notebooks"]')
action=ActionChains(driver)
action.move_to_element(laptops).perform()
time.sleep(4)
laptops_2=driver.find_element(By.XPATH,"//a[normalize-space()='Show AllLaptops & Notebooks']")
time.sleep(3)
laptops_2.click()
time.sleep(1)
HP=driver.find_element(By.XPATH,"//a[normalize-space()='HP LP3065']")
HP.click()
add_to_cart_2=driver.find_element(By.XPATH,"//button[@id='button-cart']")
add_to_cart_2.location_once_scrolled_into_view
time.sleep(2)

calendar=driver.find_element(By.XPATH,'//body')
calendar.click()

time.sleep(1)
# next_click_calendar=driver.find_element(By.XPATH,"//div[@class='datepicker-days']//th[@class='next'][contains(text(),'›')]")
# month_year=driver.find_element(By.XPATH,"//th[@class='picker-switch']")
# while month_year.text != 'December 2023':
#     next_click_calendar.click()
# time.sleep(3)
# calendar_date=driver.find_element(By.XPATH,"//td[text('31')]")
add_to_cart_2.click()
time.sleep(2)
add_to_cart_2.click()
time.sleep(1)
go_to_cart=driver.find_element(By.ID,'cart-total')
go_to_cart.click()
time.sleep(1)
checkout=driver.find_element(By.XPATH,"//a[@title='Checkout']//i[@class='fa fa-share']")
checkout.click()
time.sleep(1)
guest=driver.find_element(By.XPATH,"//input[@value='guest']")
guest.click()
continue_1=driver.find_element(By.XPATH,'//input[@id="button-account"]')
continue_1.click()
time.sleep(1)

step_2=driver.find_element(By.XPATH,"//div[@id='checkout-checkout']//div[2]//div[1]//h4[1]") 
step_2.location_once_scrolled_into_view
time.sleep(2)
first_name=driver.find_element(By.XPATH,"//input[@id='input-payment-firstname']")
first_name.click()
time.sleep(1)
first_name.send_keys('Divya')
# last name
last_name=driver.find_element(By.XPATH,"//input[@id='input-payment-lastname']")
last_name.click()
time.sleep(1)
last_name.send_keys('Chauhan')
# email
email=driver.find_element(By.XPATH,"//input[@id='input-payment-email']")
email.click()
time.sleep(1)
email.send_keys('divyabwr30702@gmail.com')
# telephone
telephone=driver.find_element(By.XPATH,"//input[@id='input-payment-telephone']")
telephone.click()
time.sleep(1)
telephone.send_keys('7014330870')
# company
company=driver.find_element(By.XPATH,"//input[@id='input-payment-company']")
company.click()
time.sleep(1)
company.send_keys('Celebal Technologies')
# address
address=driver.find_element(By.XPATH,"//input[@id='input-payment-address-1']")
address.click()
time.sleep(1)
address.send_keys('Malviya Nagar')
# city
city=driver.find_element(By.XPATH,"//input[@id='input-payment-city']")
city.click()
time.sleep(1)
city.send_keys('Jaipur')
# code
code=driver.find_element(By.XPATH,"//input[@id='input-payment-postcode']")
code.click()
time.sleep(1)
code.send_keys('305901')
# country
country=driver.find_element(By.XPATH,"//select[@id='input-payment-country']")
dropdown=Select(country)
time.sleep(1)
dropdown.select_by_visible_text('India')
time.sleep(1)
# region_
region=driver.find_element(By.XPATH,"//select[@id='input-payment-zone']")
dropdown_2=Select(region)
time.sleep(1)
dropdown_2.select_by_visible_text('Rajasthan')
time.sleep(1)
continue_=driver.find_element(By.XPATH,"//input[@id='button-guest']")
continue_.click()
time.sleep(1)

continue_3=driver.find_element(By.XPATH,"//input[@id='button-shipping-method']")
continue_3.click()
time.sleep(3)
tick=driver.find_element(By.XPATH,"//input[@name='agree']")
tick.click()
time.sleep(2)

continue_4=driver.find_element(By.XPATH,"//input[@id='button-payment-method']")
continue_4.click()
confirm_order=driver.find_element(By.XPATH,"//input[@id='button-confirm']")
confirm_order.click()
if "Your order has been placed!" in driver.page_source:
        print("Order Confirmed")
driver.close()